// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });
import dotenv from 'dotenv';

// Загружаем .env из текущей папки
dotenv.config();

// Экспортируем конфиг
export default {
  schema: 'prisma/schema.prisma',  // Путь относительно корня проекта
  datasource: {
    url: process.env.DATABASE_URL,
    // url: "postgresql://todo_user:123456@192.168.1.52:5432/todo_db?schema=public"
  },
};